# Generated by Django 4.2 on 2023-05-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_images_delete_imageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.BooleanField(choices=[(True, 'nuevo'), (False, 'usado')], default='nuevo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagenes'),
        ),
    ]
