# Generated by Django 4.2 on 2023-05-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_options_image_alter_item_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagenes'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
