# Generated by Django 4.2 on 2023-05-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_images_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.BooleanField(choices=[(True, 'nuevo'), (False, 'usado')], default='nuevo', verbose_name='Condicion'),
        ),
    ]
