# Generated by Django 4.2 on 2023-05-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_category_parent_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
