# Generated by Django 4.2 on 2023-05-19 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_sold',
            new_name='sold',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='otros', max_length=100, unique=True, verbose_name='Titulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(related_name='items', to='items.image', verbose_name='Imagenes'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(verbose_name='Precio'),
        ),
    ]
