# Generated by Django 4.2 on 2023-05-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.CharField(blank=True, max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
    ]
