# Generated by Django 4.2 on 2023-05-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_rename_is_sold_item_sold_remove_item_name_item_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagenes'),
        ),
    ]
