# Generated by Django 4.2 on 2023-05-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_remove_item_images_delete_image_item_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Modelo'),
        ),
    ]
