# Generated by Django 4.2 on 2023-05-20 03:39

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_item_brand_item_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(null=True, upload_to=items.models.image_upload_custom, verbose_name='Imagenes'),
        ),
    ]
